class LocationService {
  // Local static data for countries and states to prevent heavy backend calls
  static const Map<String, List<String>> _countryStates = {
    'United States': [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'New York',
      'Texas',
      'Washington',
    ],
    'Vietnam': [
      'An Giang',
      'Ba Ria - Vung Tau',
      'Bac Giang',
      'Bac Kan',
      'Bac Lieu',
      'Bac Ninh',
      'Ben Tre',
      'Binh Dinh',
      'Binh Duong',
      'Binh Phuoc',
      'Binh Thuan',
      'Ca Mau',
      'Can Tho',
      'Cao Bang',
      'Da Nang',
      'Dak Lak',
      'Dak Nong',
      'Dien Bien',
      'Dong Nai',
      'Dong Thap',
      'Gia Lai',
      'Ha Giang',
      'Ha Nam',
      'Ha Noi',
      'Ha Tinh',
      'Hai Duong',
      'Hai Phong',
      'Hau Giang',
      'Hoa Binh',
      'Ho Chi Minh City',
      'Hung Yen',
      'Khanh Hoa',
      'Kien Giang',
      'Kon Tum',
      'Lai Chau',
      'Lam Dong',
      'Lang Son',
      'Lao Cai',
      'Long An',
      'Nam Dinh',
      'Nghe An',
      'Ninh Binh',
      'Ninh Thuan',
      'Phu Tho',
      'Phu Yen',
      'Quang Binh',
      'Quang Nam',
      'Quang Ngai',
      'Quang Ninh',
      'Quang Tri',
      'Soc Trang',
      'Son La',
      'Tay Ninh',
      'Thai Binh',
      'Thai Nguyen',
      'Thanh Hoa',
      'Thua Thien Hue',
      'Tien Giang',
      'Tra Vinh',
      'Tuyen Quang',
      'Vinh Long',
      'Vinh Phuc',
      'Yen Bai',
    ],
    'United Kingdom': [
      'England',
      'Scotland',
      'Wales',
      'Northern Ireland',
    ],
    'Uzbekistan': [
      'Tashkent',
      'Samarkand',
      'Bukhara',
      'Andijan',
      'Fergana',
      'Khiva',
    ],
    'Uruguay': [
      'Montevideo',
      'Canelones',
      'Maldonado',
      'Salto',
    ],
    'Vanuatu': [
      'Malampa',
      'Penama',
      'Sanma',
      'Shefa',
    ],
    'Venezuela': [
      'Caracas',
      'Zulia',
      'Miranda',
      'Carabobo',
    ],
    'Yemen': [
      'Sanaa',
      'Aden',
      'Taiz',
      'Al Hudaydah',
    ],
    'Zambia': [
      'Lusaka',
      'Copperbelt',
      'Central',
      'Southern',
    ]
  };

  static List<String> getCountries() {
    return _countryStates.keys.toList()..sort();
  }

  static List<String> getStatesForCountry(String country) {
    if (!_countryStates.containsKey(country)) return [];
    return List<String>.from(_countryStates[country]!)..sort();
  }
}
